### ISSUE TITLE
Exporting to CSV

### ISSUE THREAD

**Issue by codyogden** [codyogden/time#18]
We can post links and tutorials when we find them on how we can solve this.

**Comment by codyogden** [comment]
@mhwalsh provided us this tutorial: https://github.com/mhwalsh/test-download

**Comment by johnark88** [comment]
https://github.com/agershun/alasql/wiki

**Comment by johnark88** [comment]
This Library Works. Just tried it on a new branch. Saved all employees to CSV

**Comment by codyogden** [comment]
Awesome solution!
